package com.kairos.config;

import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Serves the Digital Asset Links file for the Android app (a Trusted Web Activity
 * generated by PWABuilder). Chrome fetches {@code /.well-known/assetlinks.json} to
 * confirm this site and the app share an owner; once verified, the installed app
 * launches full-screen with no browser address bar.
 *
 * <p>The package name and signing-certificate SHA-256 fingerprint below are public
 * by design (they identify, not authenticate, the app) and must match the key the
 * distributed APK is signed with.
 */
@RestController
public class WellKnownController {

    private static final String ASSET_LINKS = """
            [{
              "relation": ["delegate_permission/common.handle_all_urls"],
              "target": {
                "namespace": "android_app",
                "package_name": "app.railway.up.urkairos.twa",
                "sha256_cert_fingerprints": ["54:85:9F:CB:CB:87:32:3A:BA:72:EB:7D:DB:F7:5D:F6:62:33:97:B8:26:96:DD:D3:79:FD:F1:CA:0C:59:2F:9E"]
              }
            }]
            """;

    @GetMapping(value = "/.well-known/assetlinks.json", produces = MediaType.APPLICATION_JSON_VALUE)
    public String assetLinks() {
        return ASSET_LINKS;
    }
}
